window.auraSiteConfig = {
  catalogVersion: '2026-07-24-healthcare-v7',
  useAiPackagingImages: true,
  siteName: 'AuraTrace',
  contactEmail: 'hello@auratrace.co.uk',
  whatsappNumber: '447575630141',
  ownerPhone: '447733341867',
  ownerEmail: 'farmaanrai0@gmail.com',
  freeDeliveryThreshold: 30,
  discountCode: 'WELCOME15',
  bankDetails: 'Account name: AuraTrace\nSort code: UPDATE-ME\nAccount number: UPDATE-ME\nReference: Your name + product\n\nReplace these details in site-config.js when ready.',
  placeholderImage: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
  stripePublishableKey: 'pk_live_51Twdp0Gb6eszdT6dX3IOinseo0UmJ6IQPnYqXTNr4IRzOhAHusI2NwVIeirgXgG5UQQVbm1xcel2kItiN9yxyRdf0015a6Vv9X',
  stripePaymentLinks: {
  "1001": "https://buy.stripe.com/fZu28rgAJbUldjiaG02sM0h",
  "1007": "https://buy.stripe.com/6oUdR91FPaQh9326pK2sM0i",
  "1011": "https://buy.stripe.com/bJe9ATesBe2tfrq9BW2sM0j",
  "1014": "https://buy.stripe.com/eVq9AT84d6A1bbacO82sM0k",
  "1017": "https://buy.stripe.com/28E28r2JTe2t6UUeWg2sM0l",
  "1018": "https://buy.stripe.com/aFabJ184d6A1enm7tO2sM0m",
  "1020": "https://buy.stripe.com/9B6bJ1acl5vX6UU29u2sM0n",
  "1022": "https://buy.stripe.com/7sYeVdgAJcYp5QQcO82sM0o",
  "1023": "https://buy.stripe.com/9B69ATcktbUl0ww5lG2sM0p",
  "1024": "https://buy.stripe.com/7sYcN5ckt6A12EEeWg2sM0q",
  "1025": "https://buy.stripe.com/6oUaEX1FP1fHcfe9BW2sM0r",
  "1026": "https://buy.stripe.com/6oU7sLdox9MdbbadSc2sM0s",
  "1027": "https://buy.stripe.com/28E4gzaclaQh5QQ5lG2sM0t",
  "1029": "https://buy.stripe.com/aFa6oHgAJf6xa769BW2sM0u",
  "1030": "https://buy.stripe.com/00w14ndox1fH7YY7tO2sM0v",
  "1032": "https://buy.stripe.com/3cI14nfwF8I93II15q2sM0w",
  "1033": "https://buy.stripe.com/cNi8wP2JT1fH0ww9BW2sM0x",
  "2001": "https://buy.stripe.com/5kQ5kD5W51fH1AA7tO2sM0y",
  "2002": "https://buy.stripe.com/cNi9AT1FP0bDa7629u2sM0z",
  "2003": "https://buy.stripe.com/6oU4gzesB2jLdji8xS2sM0A",
  "2004": "https://buy.stripe.com/4gM14n0BL2jL0wweWg2sM0B",
  "2005": "https://buy.stripe.com/7sYeVd2JT4rTenm29u2sM0C",
  "2006": "https://buy.stripe.com/8x2aEXesB3nPdji29u2sM0D",
  "2007": "https://buy.stripe.com/28E00jgAJ2jLenm9BW2sM0E",
  "2008": "https://buy.stripe.com/00w00j7093nPbbaeWg2sM0F",
  "2009": "https://buy.stripe.com/bJe9ATgAJ2jL6UU29u2sM0G",
  "2010": "https://buy.stripe.com/3cI4gz98h0bD3IIeWg2sM0H",
  "2011": "https://buy.stripe.com/28E4gz5W58I9bba3dy2sM0I",
  "2012": "https://buy.stripe.com/aFa9AT5W5f6xgvucO82sM0J"
},
  defaultProducts: [
    {
      id: 1001,
      name: 'AuraTrace Suraksha Herbal Tea',
      price: 9.99,
      category: 'Health Care | Tea',
      description: 'Daily herbal tea blend for seasonal wellness and light digestive comfort. Pack size: 100 g tea blend.',
      image: '',
      labelSeries: 'Daily Defense Label',
      benefits: ['Supports seasonal wellness routines.', 'Helps keep digestion calm after meals.'],
      quantity: 30
    },
    {
      id: 1007,
      name: 'AuraTrace Apamarga Kshara Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Herbal tablet support for urinary and cleansing routines. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Urinary Balance Label',
      benefits: ['Supports urinary comfort in daily routines.', 'Aids internal cleansing support plans.'],
      quantity: 30
    },
    {
      id: 1011,
      name: 'AuraTrace Arjuna Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Arjuna-based daily support for active lifestyle routines. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Cardio Care Label',
      benefits: ['Traditionally used for heart wellness support.', 'Helps maintain daily vitality balance.'],
      quantity: 30
    },
    {
      id: 1014,
      name: 'AuraTrace Ashwagandha Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Adaptogenic ashwagandha tablets for stress and stamina support. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Stress Ease Label',
      benefits: ['Helps support calm stress response.', 'Supports stamina during busy schedules.'],
      quantity: 30
    },
    {
      id: 1017,
      name: 'AuraTrace Ashwagandha + Ayush Kwath Combo',
      price: 27.99,
      category: 'Health Care | Immunity Combo',
      description: 'Stress and seasonal support combo. Quantity: 60 tablets + 100 g kwath blend.',
      image: '',
      labelSeries: 'Immunity Duo Label',
      benefits: ['Supports stress balance and immunity routines.', 'Combo format improves daily consistency.'],
      quantity: 30
    },
    {
      id: 1018,
      name: 'AuraTrace Brahmi Tablets',
      price: 10.0,
      category: 'Health Care | Tablets',
      description: 'Brahmi formulation for focus and mental clarity routines. Quantity: 30 tablets.',
      image: '',
      labelSeries: 'Focus Support Label',
      benefits: ['Supports focus during study or work.', 'Helps maintain mental clarity daily.'],
      quantity: 30
    },
    {
      id: 1020,
      name: 'AuraTrace Giloy Tablets',
      price: 10.0,
      category: 'Health Care | Tablets',
      description: 'Giloy tablets for daily resilience support. Quantity: 30 tablets.',
      image: '',
      labelSeries: 'Resilience Label',
      benefits: ['Supports natural immune resilience.', 'Useful for everyday wellness plans.'],
      quantity: 30
    },
    {
      id: 1022,
      name: 'AuraTrace Power Plus Tablets',
      price: 10.0,
      category: 'Health Care | Tablets',
      description: 'Daily vitality support in a compact 30-tablet pack. Quantity: 30 tablets.',
      image: '',
      labelSeries: 'Vitality Label',
      benefits: ['Supports daily energy and stamina.', 'Compact 30-tablet starter quantity.'],
      quantity: 30
    },
    {
      id: 1023,
      name: 'AuraTrace Pustihar Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Comprehensive wellness support formula. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Nourish Label',
      benefits: ['Supports daily nourishment and strength.', 'Balanced formula for regular routines.'],
      quantity: 30
    },
    {
      id: 1024,
      name: 'AuraTrace Sugar Fit Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Herbal blood-sugar support blend for daily wellness plans. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Metabolic Balance Label',
      benefits: ['Supports metabolic wellness routines.', 'Helps maintain day-to-day balance.'],
      quantity: 30
    },
    {
      id: 1025,
      name: 'AuraTrace Slim Rattan Tablets',
      price: 10.0,
      category: 'Health Care | Tablets',
      description: 'Weight-management support with appetite and metabolism focus. Quantity: 30 tablets.',
      image: '',
      labelSeries: 'Lean Support Label',
      benefits: ['Supports appetite and weight goals.', 'Helps maintain active lifestyle routines.'],
      quantity: 30
    },
    {
      id: 1026,
      name: 'AuraTrace Slim Rattan Granules',
      price: 13.99,
      category: 'Health Care | Granules',
      description: 'Convenient granule format for weight routine support. Quantity: 200 g.',
      image: '',
      labelSeries: 'Lean Support Label',
      benefits: ['Supports weight-management routines.', 'Granule format blends easily into plans.'],
      quantity: 30
    },
    {
      id: 1027,
      name: 'AuraTrace Madhumay Rakshak Granules',
      price: 13.99,
      category: 'Health Care | Granules',
      description: 'Granule blend designed for glucose and metabolic balance plans. Quantity: 200 g.',
      image: '',
      labelSeries: 'Metabolic Balance Label',
      benefits: ['Supports glucose-aware daily routines.', 'Granule format for flexible intake.'],
      quantity: 30
    },
    {
      id: 1029,
      name: 'AuraTrace Dard Rakshak Tablets',
      price: 10.0,
      category: 'Health Care | Tablets',
      description: 'Pain-relief support tablets with herb-inspired anti-inflammatory profile. Quantity: 30 tablets.',
      image: '',
      labelSeries: 'Joint Comfort Label',
      benefits: ['Supports comfort for active joints.', 'Helps maintain movement with ease.'],
      quantity: 30
    },
    {
      id: 1030,
      name: 'AuraTrace Dard Rakshak Oil',
      price: 8.99,
      category: 'Health Care | Oil',
      description: 'Topical wellness oil for muscle and joint comfort routines. Quantity: 100 ml.',
      image: '',
      labelSeries: 'Topical Relief Label',
      benefits: ['Supports local muscle relaxation.', 'Helps soothe stiffness after activity.'],
      quantity: 30
    },
    {
      id: 1032,
      name: 'AuraTrace Gynae Plus Tablets',
      price: 17.99,
      category: 'Health Care | Tablets',
      description: 'Women wellness support formulation for balance and vitality. Quantity: 60 tablets.',
      image: '',
      labelSeries: 'Women Wellness Label',
      benefits: ['Supports women wellness balance routines.', 'Helps maintain daily vitality support.'],
      quantity: 30
    },
    {
      id: 1033,
      name: 'AuraTrace Ayush Kwath',
      price: 9.49,
      category: 'Health Care | Kwath',
      description: 'Classical herbal decoction mix for seasonal and respiratory support. Quantity: 100 g.',
      image: '',
      labelSeries: 'Seasonal Guard Label',
      benefits: ['Supports respiratory comfort in seasonal changes.', 'Classic kwath profile for daily use.'],
      quantity: 30
    },
    {
      id: 2001,
      name: 'Underweight to Healthy Weight Plan (Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Evidence-based gradual weight gain using nutrient-dense foods. Focus on protein, healthy fats, and complex carbohydrates. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Gradual healthy weight gain approach.', 'Nutrient-dense food focus.'],
      quantity: 999
    },
    {
      id: 2002,
      name: 'Underweight to Healthy Weight Plan (Non-Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Structured weight gain plan including lean meats, fish, and eggs. Optimized for healthy muscle development. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Lean protein inclusion for muscle development.', 'Structured weight gain approach.'],
      quantity: 999
    },
    {
      id: 2003,
      name: 'Overweight Weight Loss Plan (Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Calorie-controlled vegetarian plan for sustainable weight loss. High fiber, adequate protein, and portion guidance. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Sustainable weight loss approach.', 'High fiber and adequate protein.'],
      quantity: 999
    },
    {
      id: 2004,
      name: 'Overweight Weight Loss Plan (Non-Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Balanced non-vegetarian weight loss plan with lean proteins. Includes portion control and meal timing strategies. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Lean protein focus.', 'Portion control and meal timing.'],
      quantity: 999
    },
    {
      id: 2005,
      name: 'Obese Weight Loss Plan (Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Comprehensive vegetarian plan for significant weight loss. Low-calorie density, high satiety foods with medical supervision note. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Low-calorie density foods.', 'High satiety approach.'],
      quantity: 999
    },
    {
      id: 2006,
      name: 'Obese Weight Loss Plan (Non-Vegetarian)',
      price: 2.99,
      category: 'Diet Plan | BMI Weight Loss',
      description: 'Structured non-vegetarian plan for obesity management. Includes lean protein focus and behavioral guidance. Digital delivery via email.',
      image: '',
      labelSeries: 'BMI Plan Label',
      benefits: ['Lean protein focus.', 'Behavioral guidance included.'],
      quantity: 999
    },
    {
      id: 2007,
      name: 'DASH Diet Plan for Hypertension (Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'Clinically proven DASH eating pattern adapted for vegetarians. Rich in fruits, vegetables, low-fat dairy, and potassium. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['DASH diet pattern for blood pressure.', 'Rich in fruits and vegetables.'],
      quantity: 999
    },
    {
      id: 2008,
      name: 'DASH Diet Plan for Hypertension (Non-Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'DASH diet with lean meats and fish. Sodium-controlled, potassium-rich meal plan for blood pressure management. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['Sodium-controlled approach.', 'Potassium-rich meal plan.'],
      quantity: 999
    },
    {
      id: 2009,
      name: 'Diabetes Management Plan (Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'Low-GI vegetarian plan for blood sugar control. High fiber, adequate protein, carb timing strategies. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['Low-GI approach for blood sugar.', 'Carb timing strategies.'],
      quantity: 999
    },
    {
      id: 2010,
      name: 'Diabetes Management Plan (Non-Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'Diabetes-friendly non-vegetarian plan with lean proteins. Focus on glycemic control and portion management. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['Glycemic control focus.', 'Portion management included.'],
      quantity: 999
    },
    {
      id: 2011,
      name: 'Anti-Inflammatory Arthritis Plan (Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'Mediterranean-style vegetarian plan rich in omega-3s and antioxidants. Designed to reduce joint inflammation. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['Omega-3 rich foods.', 'Antioxidant focus.'],
      quantity: 999
    },
    {
      id: 2012,
      name: 'Anti-Inflammatory Arthritis Plan (Non-Vegetarian)',
      price: 5.99,
      category: 'Diet Plan | Health Condition',
      description: 'Anti-inflammatory plan including fatty fish and lean proteins. Turmeric, ginger, and omega-3 rich foods for joint comfort. Digital delivery via email.',
      image: '',
      labelSeries: 'Health Condition Label',
      benefits: ['Fatty fish inclusion.', 'Turmeric and ginger focus.'],
      quantity: 999
    }
  ]
};
